services:
   mysql:
      image: mysql:5.7
      container_name: mysql
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
      restart: always

   phpmyadmin:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql
      restart: always